window.Modernizr=function(g,c,w){function h(b,s){for(var e in b)if(p[b[e]]!==w)return"pfx"==s?b[e]:!0;return!1}var n={},y=c.documentElement;c.head||c.getElementsByTagName("head");var q=c.createElement("modernizr"),p=q.style,m=["Webkit","Moz","O","ms","Khtml"],q={},r=[],t=function(b,s,e,a){var d,i=c.createElement("div");if(parseInt(e,10))for(;e--;)d=c.createElement("div"),d.id=a?a[e]:"modernizr"+(e+1),i.appendChild(d);e=["&shy;<style>",b,"</style>"].join("");i.id="modernizr";i.innerHTML+=e;y.appendChild(i);
b=s(i,b);i.parentNode.removeChild(i);return!!b},k,u={}.hasOwnProperty,l;typeof u!==w&&typeof u.call!==w?l=function(b,a){return u.call(b,a)}:l=function(b,a){return a in b&&typeof b.constructor.prototype[a]===w};q.video=function(){var b=c.createElement("video"),a=!1;try{if(a=!!b.canPlayType)a=new Boolean(a),a.ogg=b.canPlayType('video/ogg; codecs="theora"'),a.h264=b.canPlayType('video/mp4; codecs="avc1.42E01E"')||b.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"'),a.webm=b.canPlayType('video/webm; codecs="vp8, vorbis"')}catch(e){}return a};
for(var v in q)l(q,v)&&(k=v.toLowerCase(),n[k]=q[v](),r.push((n[k]?"":"no-")+k));p.cssText="";q=null;if(g.attachEvent&&(k=c.createElement("div"),k.innerHTML="<elem></elem>",1!==k.childNodes.length)){k=function(b){for(var a=-1;++a<z;)b.createElement(x[a])};g.iepp=g.iepp||{};var f=g.iepp;l=f.html5elements||"abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video";var x=l.split("|"),z=x.length,D=RegExp("(^|\\s)("+
l+")","gi"),G=RegExp("<(/*)("+l+")","gi"),E=/^\s*[\{\}]\s*$/,F=RegExp("(^|[^\\n]*?\\s)("+l+")([^\\n]*)({[\\n\\w\\W]*?})","gi"),d=c.createDocumentFragment(),A=c.documentElement;l=A.firstChild;var j=c.createElement("body"),B=c.createElement("style"),o=/print|all/,a;f.getCSS=function(b,a){if(b+""===w)return"";for(var e=-1,d=b.length,c,i=[];++e<d;)c=b[e],c.disabled||(a=c.media||a,o.test(a)&&i.push(f.getCSS(c.imports,a),c.cssText),a="all");return i.join("")};f.parseCSS=function(a){for(var d=[],e;null!=
(e=F.exec(a));)d.push(((E.exec(e[1])?"\n":e[1])+e[2]+e[3]).replace(D,"$1.iepp_$2")+e[4]);return d.join("\n")};f.writeHTML=function(){var b=-1;for(a=a||c.body;++b<z;)for(var s=c.getElementsByTagName(x[b]),e=s.length,o=-1;++o<e;)0>s[o].className.indexOf("iepp_")&&(s[o].className+=" iepp_"+x[b]);d.appendChild(a);A.appendChild(j);j.className=a.className;j.id=a.id;j.innerHTML=a.innerHTML.replace(G,"<$1font")};f._beforePrint=function(){B.styleSheet.cssText=f.parseCSS(f.getCSS(c.styleSheets,"all"));f.writeHTML()};
f.restoreHTML=function(){j.innerHTML="";A.removeChild(j);A.appendChild(a)};f._afterPrint=function(){f.restoreHTML();B.styleSheet.cssText=""};k(c);k(d);f.disablePP||(l.insertBefore(B,l.firstChild),B.media="print",B.className="iepp-printshim",g.attachEvent("onbeforeprint",f._beforePrint),g.attachEvent("onafterprint",f._afterPrint))}n._version="2.0.4";n._prefixes=" -webkit- -moz- -o- -ms- -khtml-".split(" ");n._domPrefixes=m;n.mq=function(a){if(g.matchMedia)return matchMedia(a).matches;var d;t("@media "+
a+" { #modernizr { position: absolute; } }",function(a){d="absolute"==(g.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position});return d};n.testProp=function(a){return h([a])};n.testAllProps=function(a,d){var e=a.charAt(0).toUpperCase()+a.substr(1),e=(a+" "+m.join(e+" ")+e).split(" ");return h(e,d)};n.testStyles=t;y.className=y.className.replace(/\bno-js\b/,"")+(" js "+r.join(" "));return n}(this,this.document);
(function(g,c){function w(){x(!0)}g.respond={};respond.update=function(){};respond.mediaQueriesSupported=c;if(!c){for(var h=g.document,n=h.documentElement,y=[],q=[],p=[],m={},r=h.getElementsByTagName("head")[0]||n,t=r.getElementsByTagName("link"),k=[],u=function(){for(var d=t.length,c=0,j,f,o;c<d;c++)j=t[c],f=j.href,o=j.media,j=j.rel&&"stylesheet"===j.rel.toLowerCase(),f&&j&&!m[f]&&(!/^([a-zA-Z]+?:(\/\/)?(www\.)?)/.test(f)||f.replace(RegExp.$1,"").split("/")[0]===g.location.host?k.push({href:f,media:o}):
m[f]=!0);l()},l=function(){if(k.length){var d=k.shift();var c=d.href,j=z();j&&(j.open("GET",c,!0),j.onreadystatechange=function(){if(4==j.readyState&&(200==j.status||304==j.status)){var c=j.responseText,f=d.href,a=d.media,b=c.match(/@media[^\{]+\{([^\{\}]+\{[^\}\{]+\})+/gi),s=b&&b.length||0,f=f.substring(0,f.lastIndexOf("/")),e=function(a){return a.replace(/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,"$1"+f+"$2$3")},k=!s&&a,g=0,i,C,H,h,n;f.length&&(f+="/");for(k&&(s=1);g<s;g++){i=0;k?(C=a,q.push(e(c))):
(C=b[g].match(/@media ([^\{]+)\{([\S\s]+?)$/)&&RegExp.$1,q.push(RegExp.$2&&e(RegExp.$2)));h=C.split(",");for(n=h.length;i<n;i++)H=h[i],y.push({media:H.match(/(only\s+)?([a-zA-Z]+)(\sand)?/)&&RegExp.$2,rules:q.length-1,minw:H.match(/\(min\-width:[\s]*([\s]*[0-9]+)px[\s]*\)/)&&parseFloat(RegExp.$1),maxw:H.match(/\(max\-width:[\s]*([\s]*[0-9]+)px[\s]*\)/)&&parseFloat(RegExp.$1)})}x();m[d.href]=!0;l()}},4!=j.readyState&&j.send())}},v,f,x=function(d){var c=n.clientWidth,j="CSS1Compat"===h.compatMode&&
c||h.body.clientWidth||c,c={},g=h.createDocumentFragment(),k=t[t.length-1],a=(new Date).getTime();if(d&&v&&30>a-v)clearTimeout(f),f=setTimeout(x,30);else{v=a;for(var b in y)if(d=y[b],!d.minw&&!d.maxw||(!d.minw||d.minw&&j>=d.minw)&&(!d.maxw||d.maxw&&j<=d.maxw))c[d.media]||(c[d.media]=[]),c[d.media].push(q[d.rules]);for(b in p)p[b]&&p[b].parentNode===r&&r.removeChild(p[b]);for(b in c)d=h.createElement("style"),j=c[b].join("\n"),d.type="text/css",d.media=b,d.styleSheet?d.styleSheet.cssText=j:d.appendChild(h.createTextNode(j)),
g.appendChild(d),p.push(d);r.insertBefore(g,k.nextSibling)}},z,D=!1,G=[function(){return new ActiveXObject("Microsoft.XMLHTTP")},function(){return new XMLHttpRequest}],E=G.length;E--;){try{D=G[E]()}catch(F){continue}break}z=function(){return D};u();respond.update=u;g.addEventListener?g.addEventListener("resize",w,!1):g.attachEvent&&g.attachEvent("onresize",w)}})(this,Modernizr.mq("only all"));
(function(g,c,w){function h(){for(var a=1,b=-1;k.length-++b&&(!k[b].s||(a=k[b].r)););a&&n()}function n(){var a=k.shift();u=1;a?a.t?m(function(){if("c"==a.t){var b=c.createElement("link"),d;b.href=a.s;b.rel="stylesheet";b.type="text/css";!a.e&&(z||l)?function i(a){m(function(){if(!d)try{a.sheet.cssRules.length?(d=1,h()):i(a)}catch(b){1E3==b.code||"security"==b.message||"denied"==b.message?(d=1,m(function(){h()},0)):i(a)}},0)}(b):(b.onload=function(){d||(d=1,m(function(){h()},0))},a.e&&b.onload());
m(function(){d||(d=1,h())},o.errorTimeout);!a.e&&r.parentNode.insertBefore(b,r)}else{var e=c.createElement("script"),f;e.src=a.s;e.onreadystatechange=e.onload=function(){!f&&(!e.readyState||"loaded"==e.readyState||"complete"==e.readyState)&&(f=1,h(),e.onload=e.onreadystatechange=null)};m(function(){f||(f=1,h())},o.errorTimeout);a.e?e.onload():r.parentNode.insertBefore(e,r)}},0):(a(),h()):u=0}function y(a,b,d){var e="c"==b?G:D;u=0;b=b||"j";if(F(a)){var j=this.i++,g=function(){!C&&(!i.readyState||"loaded"==
i.readyState||"complete"==i.readyState)&&(l.r=C=1,!u&&h(),i.onload=i.onreadystatechange=null,m(function(){f.removeChild(i)},0))},i=c.createElement(e),C=0,l={t:b,s:a,e:d};i.src=i.data=a;!v&&(i.style.display="none");i.width=i.height="0";"object"!=e&&(i.type=b);i.onload=i.onreadystatechange=g;"img"==e?i.onerror=g:"script"==e&&(i.onerror=function(){l.e=l.r=1;n()});k.splice(j,0,l);f.insertBefore(i,v?null:r);m(function(){C||(f.removeChild(i),l.r=l.e=C=1,h())},o.errorTimeout)}else k.splice(this.i++,0,a),
1==k.length&&n();return this}function q(){var a=o;a.loader={load:y,i:0};return a}var p=c.documentElement,m=g.setTimeout,r=c.getElementsByTagName("script")[0],t={}.toString,k=[],u=0,l="MozAppearance"in p.style,v=l&&!!c.createRange().compareNode,f=v?p:r.parentNode,x=g.opera&&"[object Opera]"==t.call(g.opera),z="webkitAppearance"in p.style,p=z&&"async"in c.createElement("script"),D=l?"object":x||p?"img":"script",G=z?"img":D,E=Array.isArray||function(a){return"[object Array]"==t.call(a)},F=function(a){return"string"==
typeof a},d=function(a){return"[object Function]"==t.call(a)},A=[],j={},B,o;o=function(a){function b(a,b,c,e,f){var g,k=a.split("!"),l=A.length,h=k.pop(),n=k.length,h={url:h,origUrl:h,prefixes:k},o,m;for(m=0;m<n;m++)(o=j[k[m]])&&(h=o(h));for(m=0;m<l;m++)h=A[m](h);g=h;var p=g.autoCallback;if(!g.bypass){b&&(b=d(b)?b:b[a]||b[e]||b[a.split("/").pop().split("?")[0]]);if(g.instead)return g.instead(a,b,c,e,f);c.load(g.url,g.forceCSS||!g.forceJS&&/css$/.test(g.url)?"c":w,g.noexec);(d(b)||d(p))&&c.load(function(){q();
b&&b(g.origUrl,f,e);p&&p(g.origUrl,f,e)})}}function c(a,d){function e(a){if(F(a))b(a,j,d,0,f);else if("object"==typeof a)for(h in a)a.hasOwnProperty(h)&&b(a[h],j,d,h,f)}var f=!!a.test,g=a.load||a.both,j=a.callback,h;e(f?a.yep:a.nope);e(g);a.complete&&d.load(a.complete)}var e,f,g=this.yepnope.loader;if(F(a))b(a,0,g,0);else if(E(a))for(e=0;e<a.length;e++)f=a[e],F(f)?b(f,0,g,0):E(f)?o(f):"object"==typeof f&&c(f,g);else"object"==typeof a&&c(a,g)};o.addPrefix=function(a,b){j[a]=b};o.addFilter=function(a){A.push(a)};
o.errorTimeout=1E4;null==c.readyState&&c.addEventListener&&(c.readyState="loading",c.addEventListener("DOMContentLoaded",B=function(){c.removeEventListener("DOMContentLoaded",B,0);c.readyState="complete"},0));g.yepnope=q()})(this,this.document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
