function getNav(){var a=$("nav[role=navigation] fieldset[role=search]").after('<fieldset class="mobile-nav"></fieldset>').next().append("<select></select>");a.children("select").append('<option value="">Navigate&hellip;</option>');$("ul[role=main-navigation]").addClass("main-navigation");$("ul.main-navigation a").each(function(b){a.children("select").append('<option value="'+b.href+'">&raquo; '+b.text+"</option>")});$("ul.subscription a").each(function(b){a.children("select").append('<option value="'+
b.href+'">&raquo; '+b.text+"</option>")});a.children("select").bind("change",function(a){a.target.value&&(window.location.href=a.target.value)})}
function addSidebarToggler(){$("body").hasClass("sidebar-footer")||($("#content").append('<span class="toggle-sidebar"></span>'),$(".toggle-sidebar").bind("click",function(a){a.preventDefault();$("body").hasClass("collapse-sidebar")?$("body").removeClass("collapse-sidebar"):$("body").addClass("collapse-sidebar")}));var a=$("aside.sidebar > section");1<a.length&&a.each(function(b,c){a.length>=3&&c%3===0&&$(b).addClass("first");$(b).addClass((c+1)%2?"odd":"even")});3<=a.length&&$("aside.sidebar").addClass("thirds")}
function testFeatures(){$(["maskImage"]).map(function(a){Modernizr.testAllProps(a)?$("html").addClass(a):$("html").addClass("no-"+a)});"placeholder"in document.createElement("input")?$("html").addClass("placeholder"):$("html").addClass("no-placeholder")}
function addCodeLineNumbers(){"Microsoft Internet Explorer"!==navigator.appName&&$("div.gist-highlight").each(function(a){for(var b='<pre class="line-numbers">',c=$(".line",a).length,e=1;e<=c;e++)b+='<span class="line-number">'+e+"</span>\n";b='<table><tbody><tr><td class="gutter">'+b+'</pre></td><td class="code"><pre>'+$("pre",a).html()+"</pre></td></tr></tbody></table>";$(a).html(b)})}
function flashVideoFallback(){$("video").each(function(a){a=$(a);if(!Modernizr.video.h264&&swfobject.getFlashPlayerVersion()||-1!==window.location.hash.indexOf("flash-test"))a.children("source[src$=mp4]").first().map(function(b){var b=$(b).attr("src"),c="video_"+Math.round(1+1E5*Math.random()),e=a.attr("width"),i=parseInt(a.attr("height"),10)+30;a.after('<div class="flash-video"><div><div id='+c+">");swfobject.embedSWF("/assets/jwplayer/player.swf",c,e,i+30,"9.0.0",{file:b,image:a.attr("poster"),
skin:"/assets/jwplayer/glow/glow.xml"},{movie:b,wmode:"opaque",allowfullscreen:"true"})}),a.remove()})}function wrapFlashVideos(){$("object").each(function(a){a=$(a);if($("param[name=movie]",a).length){var b=a.before('<div class="flash-video"><div>').previous();$(b).children().append(a)}});$("iframe[src*=vimeo],iframe[src*=youtube]").each(function(a){var a=$(a),b=a.before('<div class="flash-video"><div>').previous();$(b).children().append(a)})}
function renderDeliciousLinks(a){for(var b="<ul>",c=0,e=a.length;c<e;c++)b+='<li><a href="'+a[c].u+'" title="Tags: '+(""==a[c].t?"":a[c].t.join(", "))+'">'+a[c].d+"</a></li>";$("#delicious").html(b+"</ul>")}$.domReady(function(){testFeatures();wrapFlashVideos();flashVideoFallback();addCodeLineNumbers();getNav();addSidebarToggler()});
(function(a){function b(){i.content="width=device-width,minimum-scale="+e[0]+",maximum-scale="+e[1];a.removeEventListener(c,b,!0)}var c="gesturestart",e=[1,1],i="querySelectorAll"in a?a.querySelectorAll("meta[name=viewport]"):[];if((i=i[i.length-1])&&"addEventListener"in a)b(),e=[0.25,1.6],a.addEventListener(c,b,!0)})(document);
var swfobject=function(){function a(a,d,c){var e,g=b(c);if(k.wk&&312>k.wk)return e;if(g)if(typeof a.id==i&&(a.id=c),k.ie&&k.win){var h="",f;for(f in a)a[f]!=Object.prototype[f]&&("data"==f.toLowerCase()?d.movie=a[f]:"styleclass"==f.toLowerCase()?h+=' class="'+a[f]+'"':"classid"!=f.toLowerCase()&&(h+=" "+f+'="'+a[f]+'"'));f="";for(var j in d)d[j]!=Object.prototype[j]&&(f+='<param name="'+j+'" value="'+d[j]+'" />');g.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+h+">"+f+"</object>";
e=b(a.id)}else{j=o.createElement(r);j.setAttribute("type",t);for(var l in a)a[l]!=Object.prototype[l]&&("styleclass"==l.toLowerCase()?j.setAttribute("class",a[l]):"classid"!=l.toLowerCase()&&j.setAttribute(l,a[l]));for(h in d)d[h]!=Object.prototype[h]&&"movie"!=h.toLowerCase()&&(a=j,f=h,l=d[h],c=o.createElement("param"),c.setAttribute("name",f),c.setAttribute("value",l),a.appendChild(c));g.parentNode.replaceChild(j,g);e=j}return e}function b(a){var d=null;try{d=o.getElementById(a)}catch(b){}return d}
function c(a){var d=k.pv,a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return d[0]>a[0]||d[0]==a[0]&&d[1]>a[1]||d[0]==a[0]&&d[1]==a[1]&&d[2]>=a[2]?!0:!1}function e(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=i?encodeURIComponent(a):a}var i="undefined",r="object",t="application/x-shockwave-flash",w=window,o=document,m=navigator,k,x=typeof o.getElementById!=i&&typeof o.getElementsByTagName!=i&&typeof o.createElement!=i,n=m.userAgent.toLowerCase(),
p=m.platform.toLowerCase(),y=p?/win/.test(p):/win/.test(n),p=p?/mac/.test(p):/mac/.test(n),n=/webkit/.test(n)?parseFloat(n.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,u=!+"\x0B1",q=[0,0,0],g=null;if(typeof m.plugins!=i&&typeof m.plugins["Shockwave Flash"]==r){if((g=m.plugins["Shockwave Flash"].description)&&!(typeof m.mimeTypes!=i&&m.mimeTypes[t]&&!m.mimeTypes[t].enabledPlugin))u=!1,g=g.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),q[0]=parseInt(g.replace(/^(.*)\..*$/,"$1"),10),q[1]=parseInt(g.replace(/^.*\.(.*)\s.*$/,
"$1"),10),q[2]=/[a-zA-Z]/.test(g)?parseInt(g.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof w.ActiveXObject!=i)try{var v=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(v&&(g=v.GetVariable("$version")))u=!0,g=g.split(" ")[1].split(","),q=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10)]}catch(z){}k={w3:x,pv:q,wk:n,ie:u,win:y,mac:p};return{embedSWF:function(b,d,e,g,o,h,f,j,l){var m={success:!1,id:d};if(k.w3&&!(k.wk&&312>k.wk)&&b&&d&&e&&g&&o){var n={};if(j&&typeof j===r)for(var p in j)n[p]=
j[p];n.data=b;n.width=e+"";n.height=g+"";b={};if(f&&typeof f===r)for(var q in f)b[q]=f[q];if(h&&typeof h===r)for(var s in h)typeof b.flashvars!=i?b.flashvars+="&"+s+"="+h[s]:b.flashvars=s+"="+h[s];c(o)&&(d=a(n,b,d),m.success=!0,m.ref=d)}l&&l(m)},ua:k,getFlashPlayerVersion:function(){return{major:k.pv[0],minor:k.pv[1],release:k.pv[2]}},hasFlashPlayerVersion:c,createSWF:function(b,d,c){if(k.w3)return a(b,d,c)},getQueryParamValue:function(a){var b=o.location.search||o.location.hash;if(b){/\?/.test(b)&&
(b=b.split("?")[1]);if(null==a)return e(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return e(b[c].substring(b[c].indexOf("=")+1))}return""}}}();
